[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.4", features = ["csr"] }
leptos_router = "0.7.4"
reqwasm = "0.5.0"
serde = { version = "1.0.217", features = ["derive"] }
