//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "medication_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub medication_type_id: i32,
    pub name: String,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pet_medication::Entity")]
    PetMedication,
}

impl Related<super::pet_medication::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PetMedication.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
