//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::medication_type::Entity as MedicationType;
pub use super::pet::Entity as Pet;
pub use super::pet_medication::Entity as PetMedication;
pub use super::pet_photo::Entity as PetPhoto;
